# import re

# value = "Hey guys Welcome Back!"

# output = re.search("Hey",value)
# print(output)


# import re

# # Search for a pattern in a string
# string = "The quick brown fox jumps over the lazy dog."
# pattern = "quick"

# if re.search(pattern, string):
#     print("Match found!")
# else:
#     print("Match not found.")



# pattern = r"^(?=.*[a-z])(?=.*[A-Z])(?=.*[!@#$%^&*()_+=-])(?=.{8,})"

# ^ =  It is use for Beginning of a string.
# [] = In a regular expression, square brackets [] are used to create a character set, which is a set of characters that you want to match.
# for example = the character set [abc] would match any of the characters a, b, or c. 
# * = symbol is a quantifier that indicates that the preceding character, group, or character class can be matched zero or more times.

s4 = R"C:\Windows\System32"
print(s4)